version: '2'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data
    network_mode: "bridge"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - /media/media3/MyTVSeries:/tv
      - /media/media2/Torrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: "bridge"
    links:
      - jackett:jackett
      - qbittorrent:qbittorrent

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - .volumes/radarr:/config
      - /media/media3/Video:/movies
      - /media/media2/Torrent:/downloads
      #- /media/media2/Torrent:/media/media2/Torrent
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: "bridge"
    links:
      - jackett:jackett
      - qbittorrent:qbittorrent

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - RUN_OPTS=run options here #optional
    volumes:
      - ./volumes/jackett/data:/config
      - /media/media2/Torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    network_mode: "bridge"

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - .volumes/qbittorrent/config:/config
      - /media/media2/Torrent:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    network_mode: "bridge"

  dokuwiki:
    image: linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_URL=/dokuwiki #optional
    volumes:
      - .volumes/docuwiki/config:/config
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped
    network_mode: "bridge"

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - .volumes/lidarr/config:/config
      - /media/media3/Music:/music
      - /media/media2/Torrent:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    network_mode: "bridge"
    links:
      - jackett:jackett
      - qbittorrent:qbittorrent
      

networks:
  default:
    external:
      name: bridge

